plugins {
    id 'java'
    id 'fabric-loom' version '1.6.7'
}

group = "fun.czw06.noairminingpenalty"
version = "1.0.0"

repositories {
    mavenCentral()
    maven { url = "https://maven.fabricmc.net/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    // 如果不需要 Fabric API，可以不加
    // modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // 用 JDK 21 编译
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 17   // 编译成 Java 17 字节码，兼容 1.16–1.21
}
