plugins {
    id 'java'
    id 'net.neoforged.gradle.userdev' version '7.0.110'
}

base {
    archivesName = "no_air_mining_penalty-neoforge-universal"
}

group = 'fun.czw06.noairminingpenalty'
version = '1.0.0'

base {
    archivesName = "no_air_mining_penalty-neoforge-${minecraft_version}"
}

java {
    // 这里规定必须用 JDK 21
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    maven {
        name = "Lss233 Minecraft Repository"
        url = 'https://lss233.littleservice.cn/repositories/minecraft'
    }
    // 其他仓库
    // ...
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
